# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WBMVVM_OCExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WBMVVM_OCExample
  pod 'YYModel'
  pod 'ReactiveObjC'
  pod 'AFNetworking'
  pod 'MJRefresh'

  target 'WBMVVM_OCExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WBMVVM_OCExampleUITests' do
    # Pods for testing
  end

end
